#!/usr/bin/env bash
# transfers dater from our client to the sever
# How to use:
#   ./0-transfer_file file_to_transfer 54.157.155.107 ubuntu ~/.ssh/school
#scp $source_path $ubuntu@$ip:$destination_path
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
