#!/usr/bin/env bash

#required to install nginx on the remote sever
# configur the default config file to listen to port 80
# making a http query should return 'hello world'

sudo apt get update
sudo apt-get -y install nginx
echo "Hello world" > /var/www/html/index.html
sudo service nginx start

