#!/usr/bin/env bash

#required to install nginx on the remote sever
# configur the default config file to listen to port 80
# making a http query should return 'hello world'

sudo apt install -y nginx
sudo apt get update
echo 'Hello world' > /var/www/html/index.nginx-debian.html
service nginx start

