#!/usr/bin/env bash
# make a page return a 404 containing a string

apt-get update
apt install -y nginx
mkdir /etc/nginx/html
echo "Hello Alex" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

echo "server{
    listen 80 default_server;
    root /etc/nginx/html;
    index index.html index,htm;
    location /redirect_me{
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}i
" >> /etc/nginx/sites-available/default

service nginx restart


