#!/usr/bin/env bash
# install HAproxy
# configure HAproxy to distribute load between web01 and web02
# Use round robin algorithm
#Make sure its managed by an init script
#Make sure your severs are configured with the correct hostnames

# enable decated PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8

#install the package
apt-get install haproxy=2.8.\*

apt update && apt upgrade -y

#backup the original file
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
# HAproxy configuration
echo "
listen appname
    bind :80
    mode http
    balance roundrobin
    option httpclose
    option httpforwardfor
    server 337569-web-01 54.157.155.107 check
    server 337569-web-02 54.174.27.176 check
" > /etc/haproxy/haproxy.cfg
sudo service haproxy restart
