#!/usr/bin/env bash
#check why nginx is not listening to port 80

sudo ufw allow 80

echo "server {\n\tlisten 80 default_server;\n\tlisten[::]:80 default_server;\n\troot /var/www/html;\n\tserver_name _;\n\tlocation / {\n\t\ttry_files $uri $uri/ =404;}" /etc/nginx/sites-available/default
