#!/usr/bin/env bash
#prints "best school" ten times using a while loop
#the condition will be true as long as th value of our variable is less than or equal to 10

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    ((i++))
done
