#!/usr/bin/env bash
#prints "Best school" ten times but 'Hi' on the 9th iteration

myvar=1
while [ $myvar -le 10 ]
do
    echo "Best School"
    if [ $myvar -eq 9 ]
    then
        echo "Hi"
    fi
    myvar=$((myvar+1))
done
