#!/usr/bin/env bash
# loops from one to 10 and prints "bad luck" -4, "good luck" -8, "Best School"-other

mynum=1
while [ $mynum -le 10 ]
do

    if [ $mynum -eq 4 ]
    then
        echo "bad luck"
    elif [ $mynum -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    mynum=$((mynum+1))
done
