#!/usr/bin/env bash
#prints hours from 0 to 12 and minutes from 1-59

Hour=0
while [ $Hour -le 12 ]
do
    
    echo "Hour:$Hour"
    mins=1
    while [ $mins -le 59 ]
    do
        echo "$mins"
        mins=$((mins+1))
    done
    Hour=$((Hour+1))
done

