#!/usr/bin/env bash
#configures Ubuntu sever: local host resolves to 127.0.0.0.2, facebook.com resolves to 8.8.8.8
# (To be run in Docker container; else revert hostfile back)
# https://web.archive.org/web/20171117023601/http://blog.jonathanargentiero.com/dock    er-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

cp /etc/hosts hosts_tmp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_tmp
cp -f hosts_tmp /etc/hosts

